apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: python-sql-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_NAME
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_USER     
     

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: python-sql-demo
spec:
  selector:
    app: mysql-db
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
  type: ClusterIP
